### ISSUE TITLE
NPC flags

### ISSUE THREAD

**Issue by sindastra** [arcemu/arcemu#124]
gossip flag (1) wont work with npc_text_localized..
for example: if i take a trainer with flag 81 (Trainer - Profession Trainer - Gossip) i have to remove the gossip (1) so i have 80 (Trainer - Profession Trainer) or it wont work (nothing happens when clicking on it but shows a little book on the cursor).. other people have same issue with localisation (npc_text_localized)..

edit: some npc which have only gossip flag (1), nothing happens when clicking them..

**Comment by sanctum32** [comment]
This issue was moved to EasyWoW/wotlk-core#67

**Comment by dfighter1985** [comment]
I've just tried this and it works fine.
I've also done some experimenting to figure out what could cause the NPCs to not response, and that happens when you don't get the NPC text from the server. However there's always an NPC text response as long as it's in the database in either a localized format or the default English format.
I can only see two possibilities at the moment:
1.) You had a bad data
2.) There was a bug that has already been fixed.

Either way, thanks for the report, but I am closing this now as it no longer applies.
