### ISSUE TITLE
Items cant be repaired

### ISSUE THREAD

**Issue by gcpigni** [arcemu/arcemu#420]
Used this commit: d4d8bb1
x32 build

Hello, i discover something broken. 

Items cant be repaired in the blacksmith. When you click in [Repair All Items] button it play the repair sound effect but item durability damage endures. Also happen with [Repair An Item]

**Comment by gcpigni** [comment]
It works now. Thank you @dfighter1985 and thank for share this kickass old project :D

**Comment by dfighter1985** [comment]
I'm glad you enjoy Arcemu!
There are two things to note here however:
1. I don't know if the repair price is correct. The price calculation is based on some DBC magic which I cannot verify. This issue that you reported was because if the item is low level and has low durability loss the repair price gets below 1 copper. So basically by rounding it up I increased the repair prices to the next whole number.
2. There's another bug with repairing items, some items are still not repaired when you click repair all, because of their bag slot. I am going to fix that too soon.
