### ISSUE TITLE
Perhaps, a short example of how to get random number between (a,b) in APE could be implemented

### ISSUE THREAD

**Issue by cressidagp** [arcemu/arcemu#431]
Greetings, I get this way from Python.org but its not working...

```
import random

print(random.randint(0,9))
```
AtributeError: module object has no attribute randint

Also tried this:

```
import _random as random
print(random.randint(0,9))
```

**Comment by dfighter1985** [comment]
Well APE uses Python 3.4, and while I removed lots of modules that are not needed for scripting, I'm fairly sure that the random module is still in there.

You could try to use random.random() with the formula

`a + (b-a) * random.random()`

where a is the lower bound and b is the upper bound. So in your case it would be:

`0 + ( 9 - 0 ) * random.random()`

...or I could export Arcemu's random calls to Python. I think this would be the best, because then you could use the same random number generator as Arcemu itself.
I think I'll do that anyways since I've just implemented the Math class (not yet commited and pushed).

**Comment by cressidagp** [comment]
wow! Son fast...

That will help a lot.

Thank uou Sir!
